"""test

Revision ID: 6a2237c91843
Revises: 
Create Date: 2021-05-20 00:00:55.747799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a2237c91843'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=10), nullable=True),
    sa.Column('new_percent', sa.Float(), nullable=True),
    sa.Column('author', sa.String(length=30), nullable=True),
    sa.Column('pub_com', sa.String(length=100), nullable=True),
    sa.Column('pub_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login_name', sa.String(length=20), nullable=True),
    sa.Column('cn_name', sa.String(length=20), nullable=True),
    sa.Column('en_name', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=5), nullable=True),
    sa.Column('nick_name', sa.String(length=20), nullable=True),
    sa.Column('birth', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('desc', sa.String(length=100), nullable=True),
    sa.Column('main_page', sa.String(length=50), nullable=True),
    sa.Column('company', sa.String(length=30), nullable=True),
    sa.Column('school', sa.String(length=30), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=10), nullable=False),
    sa.Column('detail', mysql.LONGTEXT(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='创建用户'),
    sa.Column('type', sa.Enum('public', 'private'), nullable=True),
    sa.Column('status', sa.Enum('draft', 'normal', 'delete', 'test', 'doing'), nullable=True),
    sa.Column('free', sa.Boolean(), nullable=True),
    sa.Column('like_num', sa.Integer(), nullable=True),
    sa.Column('dislike_num', sa.Integer(), nullable=True),
    sa.Column('read_num', sa.Integer(), nullable=True),
    sa.Column('pub_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_like',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'user_id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('detail', sa.String(length=200), nullable=False),
    sa.Column('img_url', sa.String(length=100), nullable=True),
    sa.Column('pub_time', sa.DateTime(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'normal', 'delete'), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment_operate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('like', 'dislike', 'collect', 'report'), nullable=True),
    sa.Column('extra', sa.String(length=200), nullable=False, comment='备注信息'),
    sa.Column('comment_id', sa.Integer(), nullable=True, comment='评论'),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_operate')
    op.drop_table('comment')
    op.drop_table('article_like')
    op.drop_table('article')
    op.drop_table('user')
    op.drop_table('books')
    # ### end Alembic commands ###
